[package]
name = "tokenizer-lib"
version = "0.3.0"
authors = ["kaleidawave <kaleidawave@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/kaleidawave/tokenizer-lib"
keywords = ["parsing", "tokenization", "utils"]
categories = ["parsing"]
description = "Tokenization utilities for building parsers in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
