dependencies = { }

[package]
name = "tokenizer-lib"
version = "1.0.0"
authors = [ "Ben <kaleidawave@gmail.com>" ]
edition = "2018"
license = "MIT"
repository = "https://github.com/kaleidawave/tokenizer-lib"
keywords = [ "parsing", "tokenization", "utils" ]
categories = [ "parsing" ]
description = "Tokenization utilities for building parsers in Rust"
