name: Crates Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'major/minor/patch or semver'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}   
      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Bump version
        run: |
          cargo install cargo-bump
          cargo bump ${{ github.event.inputs.version }} --git-tag   
      - name: Publish on crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --allow-dirty
      - name: Push updated Cargo.toml
        run: |
          git add .
          git commit -m "Release: $(git describe --tags)"
          git push --tags origin main
