name: Crates Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'major/minor/patch or semver'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}   
      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Bump version
        id: versioner
        run: echo "::set-output name=newVersion::$(deno run --allow-read --allow-write https://gist.githubusercontent.com/kaleidawave/f9cfa18fea780c09709affeb0d77f0aa/raw/2586392e96e96002c1977b65601a23b965a1c947/version-bumper.js ${{ github.event.inputs.version }})"
      - name: Publish on crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --allow-dirty
      - name: Push updated Cargo.toml
        run: |
          git tag "v${{ steps.versioner.outputs.newVersion }}"
          git add .
          git commit -m "Release: ${{ steps.versioner.outputs.newVersion }}"
          git push --tags origin main
